# Main configuration link under Admin > Configuration > Web Services
netlify_forms.admin_settings:
  title: 'Netlify Forms Settings'
  description: 'Configure Netlify API token and default settings'
  route_name: netlify_forms.admin_settings
  parent: system.admin_config_services
  weight: 10

# Customer management link under Admin > Content
netlify_forms.customers:
  title: 'Netlify Customers'
  description: 'Manage Netlify customer accounts and form access'
  route_name: entity.netlify_customer.collection
  parent: system.admin_content
  weight: 15
